### ISSUE TITLE
Javascript error on overriding errorCallback

### ISSUE THREAD

**Issue by tcinelli** [nirvana-msu/yii2-infinite-scroll#20]
Hi there, 
   Great work on the plugin, thinking about trying to help out getting this to work with infinite scroll 3.0.  I'm using all the right libs for now (v2), and trying to get the errorCallback function to work when results finished (done):
'pluginOptions' => [
         ...,
         'errorCallback' => 'function () { console.log("done");}'
]

However, I'm getting this javascript console error on 'done' event:
TypeError: opts.errorCallback.call is not a function

Any ideas?

Finally, I'd also like for the "Load more" button to not show on the final items displayed.  The functionality now is on the last page of items to load, the "Load more" buttons is displayed.  Only when this button is clicked, and loading image appears (but no more records retrieved because there is no more), does the 'finishedMsg' appear.  

I'm basically trying to display a message at the end of all items loading that says "done" and doesn't fade away, doesn't require clicking "load more" to display this.

Thanks!
Tony
